// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM23OyKv1H40fSfjoznmdpLfp-T6Bk2Ps',
    appId: '1:278560296286:web:183c5bec15a2d9ad8d53cf',
    messagingSenderId: '278560296286',
    projectId: 'pizza-restaurant-order-system',
    authDomain: 'pizza-restaurant-order-system.firebaseapp.com',
    storageBucket: 'pizza-restaurant-order-system.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2RX19ebFlq_JoCzIq14qFc7YweoHy5G0',
    appId: '1:278560296286:android:7a2882f151990e288d53cf',
    messagingSenderId: '278560296286',
    projectId: 'pizza-restaurant-order-system',
    storageBucket: 'pizza-restaurant-order-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIuJyPUfUR1MM_DbE8W98xUHCQLgVLX6I',
    appId: '1:278560296286:ios:73adc51ceeeae1998d53cf',
    messagingSenderId: '278560296286',
    projectId: 'pizza-restaurant-order-system',
    storageBucket: 'pizza-restaurant-order-system.firebasestorage.app',
    iosBundleId: 'com.example.restoOrder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIuJyPUfUR1MM_DbE8W98xUHCQLgVLX6I',
    appId: '1:278560296286:ios:73adc51ceeeae1998d53cf',
    messagingSenderId: '278560296286',
    projectId: 'pizza-restaurant-order-system',
    storageBucket: 'pizza-restaurant-order-system.firebasestorage.app',
    iosBundleId: 'com.example.restoOrder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBM23OyKv1H40fSfjoznmdpLfp-T6Bk2Ps',
    appId: '1:278560296286:web:8816728f396eff048d53cf',
    messagingSenderId: '278560296286',
    projectId: 'pizza-restaurant-order-system',
    authDomain: 'pizza-restaurant-order-system.firebaseapp.com',
    storageBucket: 'pizza-restaurant-order-system.firebasestorage.app',
  );
}
